### ISSUE TITLE
How much type normalization will objecthash do?

### ISSUE THREAD

**Issue by pedrocr** [cryptosphere/objecthash-rs#17]
These two structs hash to the same value:

```rust
struct Type1 {
  one: u32,
  two: u32,
}

struct Type2 {
  one: u16,
  two: u32,
}
```

I assume this is intended but it's definitely not what I'd want. `Hash` will differentiate between these.

**Comment by tarcieri** [comment]
objecthash is specifically targeting a JSON-like data model, and presently has no explicit "struct" support as JSON has no support for structs.

This crate provides macros which let you specify your own mapping of any data type to objecthash's JSON object-like type, but presently objecthash specifies no scheme for disambiguating objects with the same structure, nor do I believe @benlaurie plans on adding anything like that as it would go beyond the JSON-like data model.

As a hack, you could include a special key to domain separate the types, e.g. `"_type" => "Type1"`

**Comment by pedrocr** [comment]
If the model is JSON-like shouldn't all numerical values be f64 then?

**Comment by pedrocr** [comment]
Also note that my point wasn't about structs but about the fact that `objecthash(0u8) == objecthash(0u16)`. All integer types hash to the same value. It's as if all instances of `u8/u16/u32` are cast as `u64`.

**Comment by tarcieri** [comment]
For an idea of the general type model we're pursuing, I'd suggest checking out TJSON:

https://www.tjson.org/

It specifies types for `i64` and `u64` (in addition and orthogonal to `f64`), but cannot discriminate between various smaller-sized integer types.

Some alternatives to objecthash have tried being more specific to sized integer types, for example @petertodd's [proofmarshal](https://github.com/petertodd/python-proofmarshal) (I believe). I think that's a debatable point.
